### ISSUE TITLE
Creacion de select para "Categorias"

### ISSUE THREAD

**Issue by AgustinCaceresWalker** [eliasjuliana/Proyecto2Grupo4#5]
Antes de comenzar el js. Estuve viendo que dentro de mis tareas en el panel de trello estaba hacer el filtro de categorias.
Se me ocurrió implementarlo como un select, dentro del CRUD digamos. y que sea posible buscarlo tanto en busqueda filtrada por palabras "comedia", "terror", etc. o como un select cargado también dentro de la pagina de busqueda o pagina principal. 
Que contenga todas las opciones.

**Comment by eliasjuliana** [comment]
Si, me parece bien la idea, sobre todo incorporarlo a la búsqueda para el usuario. Habría que hacer el crud para registrar, editar o eliminar las categorías. Y conectar con el otro crud para agregar películas o series. Yo lo deje como un select con opciones que tendrán que tomar el valor de lo que vos crees en el crud categorías
